// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIFCPadbt4BYiNWQytCuQ5kHyZJe2IKm0',
    appId: '1:959459418560:web:6e90766d2bb5a31a536825',
    messagingSenderId: '959459418560',
    projectId: 'expenstra',
    authDomain: 'expenstra.firebaseapp.com',
    storageBucket: 'expenstra.firebasestorage.app',
    measurementId: 'G-F6K5DZTHFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GNURY1xxzfXvb0qHFB1JuQ2DsmZsuA4',
    appId: '1:959459418560:android:30cb5b143b4bfff1536825',
    messagingSenderId: '959459418560',
    projectId: 'expenstra',
    storageBucket: 'expenstra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-W9dF4sjjSEbvfHS2kJNE_MdtPLc1MIw',
    appId: '1:959459418560:ios:518be988efa7e70c536825',
    messagingSenderId: '959459418560',
    projectId: 'expenstra',
    storageBucket: 'expenstra.firebasestorage.app',
    iosBundleId: 'com.example.expensetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-W9dF4sjjSEbvfHS2kJNE_MdtPLc1MIw',
    appId: '1:959459418560:ios:518be988efa7e70c536825',
    messagingSenderId: '959459418560',
    projectId: 'expenstra',
    storageBucket: 'expenstra.firebasestorage.app',
    iosBundleId: 'com.example.expensetra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIFCPadbt4BYiNWQytCuQ5kHyZJe2IKm0',
    appId: '1:959459418560:web:652c87ff30a59363536825',
    messagingSenderId: '959459418560',
    projectId: 'expenstra',
    authDomain: 'expenstra.firebaseapp.com',
    storageBucket: 'expenstra.firebasestorage.app',
    measurementId: 'G-0VN353TDZ3',
  );
}
